<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2017-2018 <a href="seocom.ma">SEOCOM</a>.</strong> Tous dreoits réserver
</footer>
</div>
<div class="control-sidebar-bg"></div>
<!-- jQuery 3 -->
<script src="<?= WEBROOT ?>layout/js/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="<?= WEBROOT ?>layout/js/bootstrap.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/datepicker.js"></script>
<!-- SlimScroll -->
<script src="<?= WEBROOT ?>layout/js/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="<?= WEBROOT ?>layout/js/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="<?= WEBROOT ?>layout/js/adminlte.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/bootbox.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/jspdf.debug.js"></script>
<script src="<?= WEBROOT ?>layout/js/jspdf.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?= WEBROOT ?>layout/js/pace.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/demo.js"></script>
<script src="<?= WEBROOT ?>layout/js/moment.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/fullcalendar.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/locale-all.js"></script>
<script src="<?= WEBROOT ?>layout/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/select2.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/bootstrap-timepicker.min.js"></script>
<script src="<?= WEBROOT ?>layout/js/typeahead.bundle.js"></script>
<script src="<?= WEBROOT ?>layout/js/lobibox.js"></script>
<script src="<?= WEBROOT ?>layout/js/app.js"></script>


